#include "functions.c"

int morePseudoCode();
int enjoymentQuestion();
int biggestOfTwo();
int leapYear();
int textInputBirthdaySeason();
int weekPaySpent();
int multiplicationTable();
int squareCalculator();
int ellipse();
int wholeCharReal();
int threeTupleMaths();
int digitCounter();
int floatToASCII();
int inputComputation();
int supermanOrBatman();
int gradePercentToLetter();
int gameAIResponse();
int triangleTypeIdentifier();
int monthToNumberDays();
int countDownFrom70();
int steppingWithAForLoop();
int basicCalculator();
int simpleRepeater();
int factorialLoop();